### PR TITLE
HANDY-23 Apply jenkins AWS S3 storage credentials for build

### PR DESCRIPTION
**Pull request by GGoMak**

### CODE REVIEW

**Comment by GGoMak** [comment]
retest this please

**Comment by GGoMak** [comment]
retest this, please

**Comment by GGoMak** [comment]
retest this, please

**Comment by GGoMak** [comment]
retest this, please

**Comment by GGoMak** [comment]
retest this, please

**Comment by GGoMak** [comment]
retest this, please

**Review by mank1cho — APPROVED** [review]
GOOD

**Comment by GGoMak** [comment]
retest this, please

**Pull request merged**
